# Site settings
title_left: "MyLifeFrom"
title_right: "Coding" # default: ""
description: "Hyobum Lee Blog."
keywords: "development, frontend, react, nextjs, javascript, typescript, architecture, web, engineering, blog, hyobum lee, 이효범"
url: https://createhb21.github.io # site url
baseurl: "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover: "" # image uri like logo/cover image for site seo

google_analytics: G-P82C6FVXLH
twitter_username: ""
comments_enabled: false # if enabled (set to true), please provide your disqus_username
disqus_shortname: ""
postshare_enabled: false

# Build settings
permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name: "Hyobum Lee"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
